<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
namespace common\helpers;

/**
 * Description of HelpersFunctions
 *
 * @author Вадим
 */

class HelpersFunctions 
{    
    public static function arrForList($arr = array())
    {
        $new_arr = array();
        foreach($arr as $key => $value){
            $new_arr[$key] = $value['title'];
        }
        return $new_arr;
    }
    
    public static function idList($arr = array())
    {
        $new_arr = array();
        foreach($arr as $key => $value){
            $new_arr[$key] = $value['id'];
        }
        return $new_arr;
    }
    
    public static function arrForEnginesList($arr = array(), $car_title = '')
    {
        $new_arr = array();
        foreach($arr as $key => $value){
            $new_arr[$key] = $car_title . ' ' . $value['generation']['alter_title'] . ' ' . $value['title'];
        }
        return $new_arr;
    }
    
    public static function arrForObjectList($arr = array())
    {
        $new_arr = array();
        foreach($arr as $key => $value){
            $new_arr[] = $value->id;
        }
        return $new_arr;
    }
    
    public static function jobsArr()
    {
        $srv_works = array(
            array('id_work' => '7','name' => 'Замена масла в двигателе (защита снята)','type' => 'service','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2018-12-03 18:06:32','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '9','name' => 'Замена воздушного фильтра','type' => 'service','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-09-30 01:17:00','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '11','name' => 'Замена свечей зажигания','type' => 'mixed','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-08-08 14:14:19','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '13','name' => 'Замена ремня ГРМ и роликов + приводные с роликами','type' => 'mixed','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-10-14 17:30:32','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '17','name' => 'Замена жидкости системы охлаждения','type' => 'service','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-10-16 21:13:38','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '18','name' => 'Контрольный осмотр','type' => 'mixed','system' => 'diagnostika','discr'=>'диагностика узлов и систем','date_modify' => '2017-10-16 21:20:15','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '19','name' => 'Замена топливного фильтра','type' => 'service','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-10-16 21:15:44','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '20','name' => 'Замена фильтра салона','type' => 'service','system' =>  'kuzov','discr'=>'кузов','date_modify' => '2017-10-16 21:19:09','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '21','name' => 'Мойка технологическая','type' => 'mixed','system' =>  'kuzov','discr'=>'кузов','date_modify' => '2018-02-15 16:36:06','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '22','name' => 'Снять поставить защиту двигателя (пыльник)','type' => 'mixed','system' =>  'kuzov','discr'=>'кузов','date_modify' => '2018-12-03 18:04:19','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '23','name' => 'Проверка наружного освещения','type' => 'service','system' =>  'electro','discr'=>'электрики','date_modify' => '2017-09-21 15:32:46','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '25','name' => 'Замена тормозной жидкости','type' => 'service','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2017-09-21 15:26:12','date_add' => '2017-09-20 20:04:06','active' => NULL),
            array('id_work' => '40','name' => 'Замена масла в ГУ руля','type' => 'service','system' => 'podveska','discr'=>'подвески','date_modify' => '2017-10-16 21:14:29','date_add' => '2017-09-21 10:44:33','active' => NULL),
            array('id_work' => '44','name' => 'Замена свечей накаливания','type' => 'mixed','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-10-16 21:15:30','date_add' => '2017-09-30 00:44:05','active' => NULL),
            array('id_work' => '45','name' => 'Замена приводного ремня и роликов','type' => 'mixed','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2017-09-30 01:00:49','date_add' => '2017-09-30 01:00:49','active' => NULL),
            array('id_work' => '52','name' => 'Замена масла в АКПП (частичная) + сброс счетчика окисления','type' => 'service','system' => 'akpp','discr'=>'коробки передач','date_modify' => '2017-10-12 12:29:07','date_add' => '2017-10-12 12:29:07','active' => NULL),
            array('id_work' => '53','name' => 'Проверка развал-схождения','type' => 'service','system' => 'podveska','discr'=>'подвески','date_modify' => '2017-10-12 12:30:36','date_add' => '2017-10-12 12:30:36','active' => NULL),
            array('id_work' => '54','name' => 'Замена масла в муфте HALDEX','type' => 'service','system' => 'akpp','discr'=>'коробки передач','date_modify' => '2017-10-12 12:34:08','date_add' => '2017-10-12 12:34:08','active' => NULL),
            array('id_work' => '55','name' => 'Замена муфты генератора','type' => 'mixed','system' =>  'electro','discr'=>'электрики','date_modify' => '2017-10-19 11:05:03','date_add' => '2017-10-19 11:05:03','active' => NULL),
            array('id_work' => '57','name' => 'Замена масла + фильтр в КП MPS6 (робот)','type' => 'service','system' => 'akpp','discr'=>'коробки передач','date_modify' => '2018-02-16 15:05:59','date_add' => '2018-02-16 15:03:34','active' => NULL),
            array('id_work' => '59','name' => 'Диск тормозной задний (оба) + колодки (эл. ручник). Снять и установить.','type' => 'repair','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2018-07-31 15:13:42','date_add' => '2018-07-31 15:13:42','active' => NULL),
            array('id_work' => '60','name' => 'Диск тормозной задний (оба) + колодки (все). Снять и установить.','type' => 'repair','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2018-07-31 15:15:47','date_add' => '2018-07-31 15:15:47','active' => NULL),
            array('id_work' => '61','name' => 'Диск тормозной передний (оба) + колодки (все). Снять и установить.','type' => 'repair','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2018-07-31 15:17:51','date_add' => '2018-07-31 15:17:51','active' => NULL),
            array('id_work' => '62','name' => 'Колодки тормозные переднии  - замена. (колеса сняты).','type' => 'repair','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2018-08-02 13:21:23','date_add' => '2018-08-02 13:18:18','active' => NULL),
            array('id_work' => '63','name' => 'Колодки тормозные заднии - замена.','type' => 'repair','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2018-08-02 13:20:55','date_add' => '2018-08-02 13:20:55','active' => NULL),
            array('id_work' => '64','name' => 'Колодки тормозные заднии (электрич. ручник). Замена','type' => 'repair','system' =>  'tormoz','discr'=>'тормоз','date_modify' => '2018-08-02 13:23:34','date_add' => '2018-08-02 13:23:34','active' => NULL),
            array('id_work' => '65','name' => 'Амортизатор передний. Снять и установить.','type' => 'repair','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:27:07','date_add' => '2018-08-02 13:25:49','active' => NULL),
            array('id_work' => '66','name' => 'Сайлентблок переднего рычага (задний). Замена.','type' => 'repair','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:29:41','date_add' => '2018-08-02 13:28:55','active' => NULL),
            array('id_work' => '67','name' => 'Подшипник ступицы передний. Замена.','type' => 'repair','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:31:43','date_add' => '2018-08-02 13:31:43','active' => NULL),
            array('id_work' => '68','name' => 'Подшипник ступицы задний. Замена.','type' => 'repair','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:32:42','date_add' => '2018-08-02 13:32:42','active' => NULL),
            array('id_work' => '69','name' => 'Развал-схождение передняя ось. Проверить и исправить.','type' => 'mixed','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:35:34','date_add' => '2018-08-02 13:35:34','active' => NULL),
            array('id_work' => '70','name' => 'Развал-схождение 2 оси. Проверить и исправить.','type' => 'mixed','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:37:11','date_add' => '2018-08-02 13:37:11','active' => NULL),
            array('id_work' => '71','name' => 'Сайлентблоки переднего подрамника. Замена 4 шт.','type' => 'repair','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:55:37','date_add' => '2018-08-02 13:55:37','active' => NULL),
            array('id_work' => '72','name' => 'Сайлентблоки заднего подрамника. Замена 4 шт.','type' => 'repair','system' => 'podveska','discr'=>'подвески','date_modify' => '2018-08-02 13:56:52','date_add' => '2018-08-02 13:56:52','active' => NULL),
            array('id_work' => '73','name' => 'Радиатор - снять и установить','type' => 'repair','system' => 'dvigatel','discr'=>'двигателя','date_modify' => '2018-08-02 13:59:16','date_add' => '2018-08-02 13:59:16','active' => NULL),
            array('id_work' => '74','name' => 'Проверка качества охлаждающей и тормозной жидкостей (при необходимости замена)','type' => 'service','system' => 'diagnostika','discr'=>'диагностика узлов и систем','date_modify' => '2019-02-21 13:41:57','date_add' => '2019-02-21 13:41:57','active' => NULL)
          );
        
        $srv_parts = array(
            array('id_part' => '116','partName' => 'Фильтр масленный','articul' => '31372212','price' => '1000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:48:19','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '2','partName' => 'Моторное масло 0w30 Castrol A5/B5  6 л.','articul' => '156ea5 6л.','price' => '4500','original' => NULL,'vendor' => 'Castrol','date_update' => '2018-09-18 14:48:33','amount' => '208','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '4','partName' => 'Фильтр воздушный','articul' => '30680293','price' => '2000','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:26:24','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '7','partName' => 'Фильтр масленный','articul' => '8692305','price' => '930','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:48:39','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '8','partName' => 'Фильтр воздушный','articul' => '31370161','price' => '1800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:42:59','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '102','partName' => 'ГРМ комплект ОЕ','articul' => '32213096','price' => '9800','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:16:57','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '79','partName' => 'Фильтр воздушный','articul' => 'lf-1834','price' => '800','original' => NULL,'vendor' => 'Zekkert','date_update' => '2018-10-26 14:49:04','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '80','partName' => 'Фильтр воздушный','articul' => 'VO30680293','price' => '1000','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-10-26 14:49:29','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '81','partName' => 'Фильтр воздушный','articul' => 'cff100457','price' => '800','original' => NULL,'vendor' => 'CHAMPION','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '108','partName' => 'Фильтр для муфты Haldex','articul' => '9','price' => '1800','original' => '1','vendor' => 'Volvo','date_update' => '2017-10-18 14:03:42','amount' => '10','active' => NULL,'system' => NULL),
            array('id_part' => '13','partName' => 'Фильтр воздушный','articul' => '30636833','price' => '1600','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:27:02','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '100','partName' => 'ГРМ комплект б.','articul' => 'ct979k2','price' => '5700','original' => NULL,'vendor' => 'CONTITEC','date_update' => '2019-02-20 08:41:48','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '113','partName' => 'Тормозная жидкость уп.','articul' => '31400204','price' => '1100','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:42:36','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '84','partName' => 'Свеча накаливания к-т','articul' => '250403001','price' => '3000','original' => NULL,'vendor' => 'BOSCH','date_update' => '2017-10-18 14:03:42','amount' => '5','active' => NULL,'system' => NULL),
            array('id_part' => '103','partName' => 'Антифриз готовый','articul' => '31439721+h2o','price' => '2360','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 08:41:24','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '104','partName' => 'Масло для муфты Haldex','articul' => '5','price' => '2700','original' => NULL,'vendor' => 'VAG','date_update' => '2019-02-20 09:32:05','amount' => '5','active' => '1','system' => 'akpp'),
            array('id_part' => '77','partName' => 'Фильтр масленный','articul' => 'hu719/8x','price' => '650','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2018-11-12 14:28:18','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '20','partName' => 'Фильтр масленный','articul' => '1275810','price' => '680','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:30:55','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '21','partName' => 'Фильтр салона','articul' => '30630754','price' => '3000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:51:17','amount' => '10','active' => '1','system' => 'kuzov'),
            array('id_part' => '59','partName' => 'Фильтр масленный','articul' => '30750013','price' => '950','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:49:01','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '23','partName' => 'Фильтр воздушный','articul' => '8638600','price' => '1800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:43:38','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '24','partName' => 'Фильтр топливный','articul' => 'champ','price' => '800','original' => NULL,'vendor' => 'Champion','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '26','partName' => 'Фильтр топливный','articul' => '30792514','price' => '2700','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:52:55','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '27','partName' => 'Шайба поддона','articul' => '977751','price' => '115','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 14:20:56','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '28','partName' => 'Фильтр воздушный','articul' => '30745344','price' => '1800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:44:12','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '101','partName' => 'ГРМ комплект д.','articul' => '530058210','price' => '5000','original' => NULL,'vendor' => 'INA','date_update' => '2018-09-18 14:15:47','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '114','partName' => 'Тормозная жидкость уп.','articul' => '31400204-аналог','price' => '300','original' => NULL,'vendor' => 'TRV','date_update' => '2017-10-18 14:03:42','amount' => '5','active' => NULL,'system' => NULL),
            array('id_part' => '110','partName' => 'Ремень приводной с роликами','articul' => '31251250','price' => '4700','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:39:34','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '32','partName' => 'Моторное масло 0w30 Castrol A5/B5 7 л.','articul' => '156ea5 7л.','price' => '5250','original' => NULL,'vendor' => 'Castrol','date_update' => '2018-09-18 14:48:33','amount' => '208','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '34','partName' => 'Фильтр воздушный','articul' => 'zekkert','price' => '800','original' => NULL,'vendor' => 'Zekkert','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '106','partName' => 'Установочный к-т Haldex','articul' => '7','price' => '1800','original' => NULL,'vendor' => 'VAG','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'akpp'),
            array('id_part' => '107','partName' => 'Установочный к-т Haldex ОЕ','articul' => '8','price' => '3300','original' => '1','vendor' => 'Volvo','date_update' => '2018-09-18 14:48:33','amount' => '10','active' => NULL,'system' => 'akpp'),
            array('id_part' => '109','partName' => 'Масло для АКПП (4 л)','articul' => '1161640','price' => '5000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:31:12','amount' => '10','active' => '1','system' => 'akpp'),
            array('id_part' => '83','partName' => 'Шайба поддона','articul' => 'vo977751','price' => '50','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '63','partName' => 'Свечи зажигания к-т','articul' => '31216183','price' => '5300','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:41:53','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '62','partName' => 'Свечи зажигания к-т','articul' => '8692071','price' => '3800','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:27:37','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '60','partName' => 'Фильтр салона','articul' => 'k1126a','price' => '1000','original' => NULL,'vendor' => 'FILTRON','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'kuzov'),
            array('id_part' => '61','partName' => 'Свечи зажигания к-т','articul' => '30731383','price' => '5700','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:28:11','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '71','partName' => 'Фильтр воздушный','articul' => 'gparts','price' => '1000','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '45','partName' => 'Фильтр воздушный','articul' => '30636551','price' => '2000','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:31:36','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '68','partName' => 'ГРМ комплект с роликами ОЕ','articul' => '31359568','price' => '9800','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:17:20','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '67','partName' => 'ГРМ комплект с роликами ОЕ','articul' => '30758261/30731727','price' => '9800','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:17:45','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '66','partName' => 'Фильтр масленный','articul' => 'hu819x','price' => '600','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2018-10-26 14:11:25','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '73','partName' => 'Кольцо масленного фильтра','articul' => '30640790','price' => '250','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 13:45:58','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '74','partName' => 'Фильтр салона','articul' => '31390880','price' => '2900','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:52:01','amount' => '10','active' => '1','system' => 'kuzov'),
            array('id_part' => '75','partName' => 'Фильтр топливный','articul' => '31274940','price' => '3000','original' => '1','vendor' => 'Volvo','date_update' => '2018-10-26 14:11:25','amount' => '10','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '76','partName' => 'Фильтр топливный','articul' => '31342920','price' => '3000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 11:29:17','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '64','partName' => 'Свечи зажигания к-т','articul' => '31286359','price' => '5300','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:28:43','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '65','partName' => 'Свеча накаливания к-т','articul' => '8653880','price' => '9000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:41:25','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '69','partName' => 'Фильтр воздушный','articul' => '8638600/30636833','price' => '1800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:47:26','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '70','partName' => 'Фильтр топливный','articul' => '30620512/30636704','price' => '2600','original' => '1','vendor' => 'Volvo','date_update' => '2018-10-26 14:11:25','amount' => '10','active' => NULL,'system' => NULL),
            array('id_part' => '105','partName' => 'Масло для муфты Haldex ОЕ','articul' => '6','price' => '3700','original' => '1','vendor' => 'Volvo','date_update' => '2018-10-26 14:11:25','amount' => '10','active' => NULL,'system' => NULL),
            array('id_part' => '78','partName' => 'Фильтр масленный','articul' => 'hu925/4x','price' => '550','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '117','partName' => 'Фильтр масленный','articul' => 'hu719/8y','price' => '800','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2019-02-22 12:13:57','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '216','partName' => 'Свечи зажигания к-т','articul' => '31330450','price' => '3400','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:29:42','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '115','partName' => 'Фильтр масленный','articul' => '30788490','price' => '950','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 12:12:20','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '217','partName' => 'Свечи зажигания к-т','articul' => '30751806','price' => '4200','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-21 14:59:04','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '119','partName' => 'Ремень приводной с роликами','articul' => '31401425','price' => '6200','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:25:21','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '118','partName' => 'Ремень приводной с роликами','articul' => '31251252/312','price' => '5100','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:40:34','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '120','partName' => 'Натяжитель приводного ремня','articul' => '534010310','price' => '3100','original' => NULL,'vendor' => 'INA','date_update' => '2019-05-31 15:23:46','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '121','partName' => 'Натяжитель приводного ремня','articul' => '634031910','price' => '3500','original' => NULL,'vendor' => 'INA','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '122','partName' => 'Ремень приводной','articul' => '6dpk1825','price' => '1400','original' => NULL,'vendor' => 'CONTITEC','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '123','partName' => 'Ремень приводной','articul' => '6dpk1841','price' => '1400','original' => NULL,'vendor' => 'CONTITEC','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '124','partName' => 'Шкив ремня','articul' => '31316803','price' => '24000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:54:20','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '125','partName' => 'Шкив ремня','articul' => '535019510','price' => '5500','original' => NULL,'vendor' => 'INA','date_update' => '2018-10-26 14:11:25','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '126','partName' => 'Ремень приводной','articul' => '31251046','price' => '3100','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:24:49','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '127','partName' => 'Ремень приводной','articul' => '6pk1203','price' => '1100','original' => NULL,'vendor' => 'GATES','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '128','partName' => 'Ролик','articul' => '31401193','price' => '2900','original' => '1','vendor' => 'Volvo','date_update' => '2018-10-26 14:11:25','amount' => '10','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '129','partName' => 'Ролик','articul' => 't36367','price' => '2700','original' => NULL,'vendor' => 'GATES','date_update' => '2019-05-31 15:25:52','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '130','partName' => 'Натяжитель приводного ремня','articul' => '31401286','price' => '4800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:36:06','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '131','partName' => 'Натяжитель приводного ремня','articul' => 't38495','price' => '3900','original' => NULL,'vendor' => 'GATES','date_update' => '2019-02-20 09:36:33','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '132','partName' => 'Муфта генератора','articul' => '30750111','price' => '5300','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:21:33','amount' => '10','active' => '1','system' => 'elektro'),
            array('id_part' => '133','partName' => 'Муфта генератора','articul' => 'eg2','price' => '1400','original' => NULL,'vendor' => 'GATES','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'elektro'),
            array('id_part' => '134','partName' => 'Шкив генератора','articul' => '31316804','price' => '5500','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:53:53','amount' => '10','active' => '1','system' => 'elektro'),
            array('id_part' => '135','partName' => 'Моторное масло 5w30 Volvo A5/B5 6 л.','articul' => '31316300/31316299','price' => '5300','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 14:03:23','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '136','partName' => 'Диск тормозной XC90  задний','articul' => '31471824','price' => '5200','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 08:42:24','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '137','partName' => 'Диск тормозной XC90  задний мод 2','articul' => 'df4338','price' => '3400','original' => NULL,'vendor' => 'TRW','date_update' => '2019-05-31 15:18:09','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '138','partName' => 'Диск тормозной XC90  задний','articul' => 'nf1699076','price' => '2400','original' => NULL,'vendor' => 'NF','date_update' => '2019-02-20 08:42:44','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '139','partName' => 'Диск тормозной XC90  передний 16','articul' => '31423325','price' => '4950','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 08:44:31','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '140','partName' => 'Диск тормозной XC90  передний 16','articul' => 'df4339','price' => '3800','original' => NULL,'vendor' => 'TRW','date_update' => '2019-02-20 08:44:08','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '141','partName' => 'Диск тормозной XC90  передний 16','articul' => 'vo30736406','price' => '3000','original' => NULL,'vendor' => 'GPARTS','date_update' => '2019-05-31 15:18:35','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '142','partName' => 'Диск тормозной XC90  передний 17','articul' => '30657301','price' => '5800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 08:47:31','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '143','partName' => 'Диск тормозной XC90  передний 17','articul' => 'DF4340S','price' => '5400','original' => NULL,'vendor' => 'TRW','date_update' => '2019-05-31 15:19:03','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '144','partName' => 'Диск тормозной XC90  передний 17','articul' => '31400893','price' => '5800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 08:47:03','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '145','partName' => 'Колодки торм XC60/XC90 12- передние 17','articul' => '8DB355014541','price' => '4000','original' => NULL,'vendor' => 'HELLA PEGID','date_update' => '2019-02-20 08:48:32','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '146','partName' => 'Колодки торм XC60/XC90 12- передние 17','articul' => '30793943','price' => '5700','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 08:49:17','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '147','partName' => 'Колодки торм XC60/XC90 12- передние 17','articul' => 'gdb1821','price' => '3700','original' => NULL,'vendor' => 'TRW','date_update' => '2019-02-20 09:27:38','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '148','partName' => 'Колодки торм XC90 задние 16-','articul' => '31471265','price' => '4600','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:28:48','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '149','partName' => 'Колодки торм XC90 задние','articul' => '30793093','price' => '3900','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:28:20','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '150','partName' => 'Колодки торм XC90 задние','articul' => 'gdb1566','price' => '2400','original' => NULL,'vendor' => 'TRW','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'tormoz'),
            array('id_part' => '151','partName' => 'Колодки торм XC90 задние','articul' => 'vo30793093','price' => '1500','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'tormoz'),
            array('id_part' => '152','partName' => 'Колодки торм XC90 передние 16"','articul' => 'vo30793265','price' => '1800','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-10-26 14:21:52','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '153','partName' => 'Колодки торм XC90 передние 16','articul' => '30793265','price' => '5200','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:29:25','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '154','partName' => 'Колодки торм XC90 передние 16"','articul' => 'gdb1576','price' => '3600','original' => NULL,'vendor' => 'TRW','date_update' => '2018-10-26 14:22:56','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '155','partName' => 'Колодки торм XC90 16- передние 18','articul' => '31476722','price' => '6200','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:27:59','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '156','partName' => 'Колодки торм XC90 передние 17','articul' => '31262705','price' => '5800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:30:01','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '157','partName' => 'Колодки торм XC90 передние 17"','articul' => '13.0460-7188.2','price' => '3900','original' => NULL,'vendor' => 'ATE','date_update' => '2018-10-26 14:26:38','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '158','partName' => 'Колодки торм XC90 передние 17','articul' => 'gdb1565','price' => '3600','original' => NULL,'vendor' => 'TRW','date_update' => '2019-02-20 09:30:30','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '159','partName' => 'Колодки торм XC90 передние 17"','articul' => 'vo31262705','price' => '2200','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-10-26 14:28:19','amount' => '5','active' => '1','system' => 'tormoz'),
            array('id_part' => '160','partName' => 'Колодки ручника S60/S80/XC90/XC70','articul' => '31262869','price' => '3850','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:19:42','amount' => '10','active' => '1','system' => 'tormoz'),
            array('id_part' => '161','partName' => 'Колодки ручника S60/S80/XC90/XC70','articul' => '986487623','price' => '1600','original' => NULL,'vendor' => 'Bosch','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'tormoz'),
            array('id_part' => '162','partName' => 'Амортизатор задний XC90 мод','articul' => '317350','price' => '4800','original' => '1','vendor' => 'SACHS','date_update' => '2018-09-18 14:48:33','amount' => '6','active' => NULL,'system' => 'podveska'),
            array('id_part' => '163','partName' => 'Амортизатор передний XC90','articul' => '314125','price' => '7700','original' => NULL,'vendor' => 'SACHS','date_update' => '2019-05-31 15:16:28','amount' => '5','active' => '1','system' => 'podveska'),
            array('id_part' => '164','partName' => 'Опора пер амортизатора XC90 резинка','articul' => '3792301','price' => '1800','original' => NULL,'vendor' => 'Lemforder','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'podveska'),
            array('id_part' => '165','partName' => 'Пыльник+отбойник  пер амортизат. 850/S70/S80/S60/XC90','articul' => '55922709','price' => '900','original' => NULL,'vendor' => 'FEBI','date_update' => '2018-10-26 14:11:25','amount' => '5','active' => NULL,'system' => 'podveska'),
            array('id_part' => '166','partName' => 'Наконечник XC70/XC90 лев','articul' => '26701.02','price' => '2850','original' => NULL,'vendor' => 'Lemforder','date_update' => '2019-05-31 15:22:12','amount' => '5','active' => '1','system' => 'podveska'),
            array('id_part' => '167','partName' => 'Наконечник XC70/XC90 прав','articul' => '26702.02','price' => '2850','original' => NULL,'vendor' => 'Lemforder','date_update' => '2019-05-31 15:23:06','amount' => '5','active' => '1','system' => 'podveska'),
            array('id_part' => '168','partName' => 'Шаровая опора XC90','articul' => '2679503','price' => '2800','original' => NULL,'vendor' => 'Lemforder','date_update' => '2018-10-26 14:11:25','amount' => '5','active' => NULL,'system' => 'podveska'),
            array('id_part' => '169','partName' => 'Подшипник ступицы XC90 пер  -2008','articul' => 'vkba3626','price' => '6500','original' => NULL,'vendor' => 'SKF','date_update' => '2019-02-20 09:37:27','amount' => '5','active' => '1','system' => 'podveska'),
            array('id_part' => '170','partName' => 'Подшипник ступицы XC90 пер  2008-','articul' => 'vkba6602','price' => '6000','original' => NULL,'vendor' => 'SKF','date_update' => '2019-02-20 09:37:52','amount' => '5','active' => '1','system' => 'podveska'),
            array('id_part' => '171','partName' => 'Подшипник ступицы XC90 зад','articul' => 'vkba3627','price' => '6500','original' => NULL,'vendor' => 'SKF','date_update' => '2019-05-31 15:24:18','amount' => '5','active' => '1','system' => 'podveska'),
            array('id_part' => '172','partName' => 'Фильтр топливный','articul' => '31430629','price' => '3000','original' => '1','vendor' => 'Volvo','date_update' => '2018-10-26 14:11:25','amount' => '10','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '173','partName' => 'Фильтр топливный','articul' => 'f026403014','price' => '2000','original' => NULL,'vendor' => 'Bosch','date_update' => '2019-02-22 11:29:53','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '174','partName' => 'Фильтр топливный','articul' => 'pu9003z','price' => '1900','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2019-02-22 11:30:20','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '175','partName' => 'Свечи зажигания к-т','articul' => '31673604','price' => '3400','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:30:14','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '176','partName' => 'Фильтр воздушный','articul' => 'vo30745344','price' => '900','original' => NULL,'vendor' => 'GPARTS','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '177','partName' => 'Фильтр воздушный','articul' => 'lf-1596','price' => '800','original' => NULL,'vendor' => 'Zekkert','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '178','partName' => 'Фильтр салона','articul' => 'cuk-2733','price' => '1500','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'kuzov'),
            array('id_part' => '218','partName' => 'Свечи зажигания к-т','articul' => '31361653','price' => '4200','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-21 14:59:39','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '189','partName' => 'Фильтр воздушный','articul' => 'LF-1015','price' => '700','original' => '0','vendor' => 'Zekkert','date_update' => '2018-11-10 14:10:50','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '179','partName' => 'Фильтр воздушный','articul' => '9454647','price' => '1700','original' => '1','vendor' => 'Volvo','date_update' => '2018-09-18 14:48:33','amount' => '10','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '180','partName' => 'Фильтр воздушный','articul' => 'lf-1683','price' => '800','original' => NULL,'vendor' => 'Zekkert','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '181','partName' => 'Фильтр воздушный','articul' => 'lf0333','price' => '800','original' => NULL,'vendor' => 'GREEN','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '182','partName' => 'Фильтр топливный','articul' => '30636704','price' => '2600','original' => '1','vendor' => 'Volvo','date_update' => '2018-10-26 14:11:25','amount' => '10','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '183','partName' => 'Фильтр топливный','articul' => 'f026402005','price' => '1000','original' => NULL,'vendor' => 'Bosch','date_update' => '2018-09-18 14:48:33','amount' => '5','active' => NULL,'system' => 'dvigatel'),
            array('id_part' => '188','partName' => 'Фильтр воздушный','articul' => '31338216','price' => '1400','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 11:56:01','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '185','partName' => 'Масло для АКПП (4 л)','articul' => 'atf3309','price' => '3000','original' => NULL,'vendor' => 'MOBIL','date_update' => '2019-02-20 09:31:36','amount' => '5','active' => '1','system' => 'akpp'),
            array('id_part' => '192','partName' => 'Фильтр воздушный','articul' => 'C29150','price' => '1500','original' => NULL,'vendor' => 'MANN FILTER','date_update' => '2019-02-22 12:09:13','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '191','partName' => 'Фильтр воздушный','articul' => 'LF-1567','price' => '750','original' => NULL,'vendor' => 'Zekkert','date_update' => '2018-11-10 14:37:03','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '190','partName' => 'Фильтр воздушный','articul' => '30757155','price' => '1700','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 11:57:15','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '193','partName' => 'Фильтр масленный','articul' => '31339023','price' => '650','original' => '1','vendor' => 'Volvo','date_update' => '2018-11-13 08:23:57','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '194','partName' => 'Фильтр масленный','articul' => 'W7008','price' => '400','original' => '0','vendor' => 'MANN FILTER','date_update' => '2018-11-12 14:23:15','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '195','partName' => 'Фильтр масленный','articul' => '31330050','price' => '650','original' => '1','vendor' => 'Volvo','date_update' => '2018-11-12 14:25:07','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '196','partName' => 'Фильтр масленный','articul' => 'W7015','price' => '400','original' => '0','vendor' => 'MANN FILTER','date_update' => '2018-11-12 14:26:46','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '197','partName' => 'Фильтр масленный','articul' => '30735878','price' => '930','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:50:24','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '198','partName' => 'Фильтр масленный','articul' => '1359941','price' => '600','original' => '0','vendor' => 'Ford','date_update' => '2018-11-12 14:30:29','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '199','partName' => 'Фильтр масленный','articul' => 'hu711/51x','price' => '500','original' => '0','vendor' => 'MANN FILTER','date_update' => '2018-11-12 14:31:51','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '200','partName' => 'Пробка поддона двигателя','articul' => '21431617','price' => '150','original' => NULL,'vendor' => 'PRO PARTS','date_update' => '2019-02-22 13:56:57','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '201','partName' => 'Шайба поддона','articul' => '21437751','price' => '50','original' => '0','vendor' => 'PRO PARTS','date_update' => '2018-11-12 14:35:32','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '202','partName' => 'Шайба поддона','articul' => '108.502','price' => '50','original' => '0','vendor' => 'ELRING','date_update' => '2018-11-12 14:36:45','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '203','partName' => 'Шайба поддона','articul' => '394.290','price' => '50','original' => '0','vendor' => 'ELRING','date_update' => '2018-11-12 14:37:43','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '204','partName' => 'Моторное масло 5w30 Volvo A5/B5 4 л.','articul' => '31316300-4','price' => '3000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 14:04:25','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '205','partName' => 'Моторное масло 5w30 Volvo A5/B5 5 л.','articul' => '31316300-5','price' => '4150','original' => '1','vendor' => 'Volvo','date_update' => '2019-05-31 15:20:46','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '206','partName' => 'Фильтр топливный','articul' => '31274952','price' => '2100','original' => '1','vendor' => 'Volvo','date_update' => '2018-11-12 14:47:29','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '207','partName' => 'Фильтр топливный','articul' => 'WK614/46','price' => '900','original' => '0','vendor' => 'MANN FILTER','date_update' => '2018-11-12 14:48:59','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '208','partName' => 'Фильтр топливный','articul' => '5517000','price' => '2600','original' => '0','vendor' => 'UFI','date_update' => '2018-11-12 14:50:02','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '209','partName' => 'Фильтр топливный','articul' => '97.3668','price' => '900','original' => NULL,'vendor' => 'SKAN TECH','date_update' => '2018-11-12 14:52:21','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '210','partName' => 'Фильтр салона','articul' => 'IF-3165K','price' => '700','original' => '0','vendor' => 'Zekkert','date_update' => '2018-11-12 15:14:20','amount' => '10','active' => '1','system' => NULL),
            array('id_part' => '211','partName' => 'Фильтр топливный','articul' => '30783135','price' => '4800','original' => '1','vendor' => 'Volvo','date_update' => '2018-11-14 20:11:25','amount' => '1','active' => '1','system' => 'dvigatel'),
            array('id_part' => '212','partName' => 'Фильтр топливный','articul' => '8653668','price' => '2800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:53:25','amount' => '1','active' => '1','system' => 'dvigatel'),
            array('id_part' => '213','partName' => 'Фильтр масленный','articul' => '31372700','price' => '930','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:50:47','amount' => '1','active' => '1','system' => 'dvigatel'),
            array('id_part' => '214','partName' => 'Фильтр воздушный','articul' => '30741485','price' => '1700','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 12:10:06','amount' => '5','active' => '1','system' => 'dvigatel'),
            array('id_part' => '215','partName' => 'Фильтр салона','articul' => '30780377','price' => '2700','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-20 09:52:30','amount' => '5','active' => '1','system' => 'kuzov'),
            array('id_part' => '219','partName' => 'Фильтр салона','articul' => '31404958','price' => '2800','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 11:04:48','amount' => '4','active' => '1','system' => 'kuzov'),
            array('id_part' => '220','partName' => 'Фильтр салона','articul' => 'k1350A','price' => '750','original' => '0','vendor' => 'FILTRON','date_update' => '2019-02-22 11:07:11','amount' => '2','active' => '1','system' => 'kuzov'),
            array('id_part' => '221','partName' => 'Фильтр топливный','articul' => '31321475','price' => '3600','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 11:18:46','amount' => '4','active' => '1','system' => 'dvigatel'),
            array('id_part' => '222','partName' => 'Фильтр топливный','articul' => '1780195','price' => '2000','original' => '0','vendor' => 'Ford','date_update' => '2019-02-22 11:19:28','amount' => '4','active' => '1','system' => 'dvigatel'),
            array('id_part' => '223','partName' => 'Фильтр топливный','articul' => '31355412','price' => '3000','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 11:21:04','amount' => '4','active' => '1','system' => 'dvigatel'),
            array('id_part' => '224','partName' => 'Шайба поддона','articul' => '30735089','price' => '150','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 13:49:30','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '225','partName' => 'Пробка поддона двигателя','articul' => '30711617','price' => '480','original' => '1','vendor' => 'Volvo','date_update' => '2019-02-22 13:57:31','amount' => '10','active' => '1','system' => 'dvigatel'),
            array('id_part' => '226','partName' => 'Моторное масло 0w30 Castrol A5/B5 4л','articul' => '156EA5 4л.','price' => '3000','original' => '0','vendor' => 'Castrol','date_update' => '2019-02-22 14:01:37','amount' => '5','active' => '1','system' => 'dvigatel')
          );
        
        $srv_parts_cars = array(
            array('id_part' => '2','id_car' => '4','id_gen' => '9'),
            array('id_part' => '2','id_car' => '2','id_gen' => '2'),
            array('id_part' => '2','id_car' => '2','id_gen' => '1'),
            array('id_part' => '2','id_car' => '8','id_gen' => '15'),
            array('id_part' => '2','id_car' => '3','id_gen' => '8'),
            array('id_part' => '2','id_car' => '3','id_gen' => '7'),
            array('id_part' => '2','id_car' => '6','id_gen' => '10'),
            array('id_part' => '2','id_car' => '6','id_gen' => '11'),
            array('id_part' => '2','id_car' => '5','id_gen' => '12'),
            array('id_part' => '2','id_car' => '5','id_gen' => '13'),
            array('id_part' => '2','id_car' => '7','id_gen' => '14'),
            array('id_part' => '2','id_car' => '9','id_gen' => '16'),
            array('id_part' => '4','id_car' => '2','id_gen' => '2'),
            array('id_part' => '4','id_car' => '2','id_gen' => '1'),
            array('id_part' => '7','id_car' => '4','id_gen' => '9'),
            array('id_part' => '7','id_car' => '2','id_gen' => '2'),
            array('id_part' => '7','id_car' => '2','id_gen' => '1'),
            array('id_part' => '7','id_car' => '8','id_gen' => '15'),
            array('id_part' => '7','id_car' => '3','id_gen' => '8'),
            array('id_part' => '7','id_car' => '3','id_gen' => '7'),
            array('id_part' => '7','id_car' => '6','id_gen' => '11'),
            array('id_part' => '7','id_car' => '5','id_gen' => '13'),
            array('id_part' => '7','id_car' => '7','id_gen' => '14'),
            array('id_part' => '8','id_car' => '4','id_gen' => '9'),
            array('id_part' => '8','id_car' => '3','id_gen' => '8'),
            array('id_part' => '8','id_car' => '3','id_gen' => '7'),
            array('id_part' => '13','id_car' => '2','id_gen' => '2'),
            array('id_part' => '13','id_car' => '2','id_gen' => '1'),
            array('id_part' => '20','id_car' => '2','id_gen' => '2'),
            array('id_part' => '20','id_car' => '2','id_gen' => '1'),
            array('id_part' => '21','id_car' => '2','id_gen' => '2'),
            array('id_part' => '21','id_car' => '2','id_gen' => '1'),
            array('id_part' => '21','id_car' => '3','id_gen' => '7'),
            array('id_part' => '23','id_car' => '2','id_gen' => '2'),
            array('id_part' => '23','id_car' => '2','id_gen' => '1'),
            array('id_part' => '24','id_car' => '2','id_gen' => '2'),
            array('id_part' => '24','id_car' => '2','id_gen' => '1'),
            array('id_part' => '25','id_car' => '2','id_gen' => '2'),
            array('id_part' => '25','id_car' => '2','id_gen' => '1'),
            array('id_part' => '26','id_car' => '2','id_gen' => '2'),
            array('id_part' => '26','id_car' => '2','id_gen' => '1'),
            array('id_part' => '26','id_car' => '3','id_gen' => '7'),
            array('id_part' => '27','id_car' => '4','id_gen' => '9'),
            array('id_part' => '27','id_car' => '2','id_gen' => '2'),
            array('id_part' => '27','id_car' => '2','id_gen' => '1'),
            array('id_part' => '27','id_car' => '8','id_gen' => '15'),
            array('id_part' => '27','id_car' => '3','id_gen' => '8'),
            array('id_part' => '27','id_car' => '3','id_gen' => '7'),
            array('id_part' => '27','id_car' => '6','id_gen' => '10'),
            array('id_part' => '27','id_car' => '6','id_gen' => '11'),
            array('id_part' => '27','id_car' => '5','id_gen' => '12'),
            array('id_part' => '27','id_car' => '5','id_gen' => '13'),
            array('id_part' => '27','id_car' => '7','id_gen' => '14'),
            array('id_part' => '27','id_car' => '9','id_gen' => '16'),
            array('id_part' => '28','id_car' => '4','id_gen' => '9'),
            array('id_part' => '28','id_car' => '3','id_gen' => '8'),
            array('id_part' => '32','id_car' => '4','id_gen' => '9'),
            array('id_part' => '32','id_car' => '2','id_gen' => '2'),
            array('id_part' => '32','id_car' => '2','id_gen' => '1'),
            array('id_part' => '32','id_car' => '8','id_gen' => '15'),
            array('id_part' => '32','id_car' => '3','id_gen' => '8'),
            array('id_part' => '32','id_car' => '3','id_gen' => '7'),
            array('id_part' => '32','id_car' => '6','id_gen' => '10'),
            array('id_part' => '32','id_car' => '6','id_gen' => '11'),
            array('id_part' => '32','id_car' => '5','id_gen' => '12'),
            array('id_part' => '32','id_car' => '5','id_gen' => '13'),
            array('id_part' => '32','id_car' => '7','id_gen' => '14'),
            array('id_part' => '32','id_car' => '9','id_gen' => '16'),
            array('id_part' => '34','id_car' => '2','id_gen' => '2'),
            array('id_part' => '34','id_car' => '2','id_gen' => '1'),
            array('id_part' => '40','id_car' => '2','id_gen' => '2'),
            array('id_part' => '40','id_car' => '2','id_gen' => '3'),
            array('id_part' => '40','id_car' => '3','id_gen' => '8'),
            array('id_part' => '40','id_car' => '3','id_gen' => '7'),
            array('id_part' => '41','id_car' => '2','id_gen' => '2'),
            array('id_part' => '41','id_car' => '2','id_gen' => '3'),
            array('id_part' => '41','id_car' => '3','id_gen' => '8'),
            array('id_part' => '41','id_car' => '3','id_gen' => '7'),
            array('id_part' => '45','id_car' => '2','id_gen' => '2'),
            array('id_part' => '45','id_car' => '2','id_gen' => '1'),
            array('id_part' => '51','id_car' => '2','id_gen' => '2'),
            array('id_part' => '51','id_car' => '2','id_gen' => '3'),
            array('id_part' => '51','id_car' => '3','id_gen' => '8'),
            array('id_part' => '51','id_car' => '3','id_gen' => '7'),
            array('id_part' => '51','id_car' => '3','id_gen' => '8'),
            array('id_part' => '51','id_car' => '3','id_gen' => '7'),
            array('id_part' => '52','id_car' => '4','id_gen' => '9'),
            array('id_part' => '52','id_car' => '2','id_gen' => '2'),
            array('id_part' => '52','id_car' => '2','id_gen' => '3'),
            array('id_part' => '52','id_car' => '8','id_gen' => '15'),
            array('id_part' => '52','id_car' => '3','id_gen' => '8'),
            array('id_part' => '52','id_car' => '3','id_gen' => '7'),
            array('id_part' => '52','id_car' => '3','id_gen' => '8'),
            array('id_part' => '52','id_car' => '3','id_gen' => '7'),
            array('id_part' => '52','id_car' => '6','id_gen' => '10'),
            array('id_part' => '52','id_car' => '6','id_gen' => '11'),
            array('id_part' => '52','id_car' => '5','id_gen' => '12'),
            array('id_part' => '52','id_car' => '5','id_gen' => '13'),
            array('id_part' => '53','id_car' => '2','id_gen' => '2'),
            array('id_part' => '53','id_car' => '2','id_gen' => '3'),
            array('id_part' => '54','id_car' => '4','id_gen' => '9'),
            array('id_part' => '54','id_car' => '2','id_gen' => '3'),
            array('id_part' => '54','id_car' => '3','id_gen' => '7'),
            array('id_part' => '54','id_car' => '6','id_gen' => '10'),
            array('id_part' => '54','id_car' => '5','id_gen' => '12'),
            array('id_part' => '54','id_car' => '5','id_gen' => '13'),
            array('id_part' => '56','id_car' => '4','id_gen' => '9'),
            array('id_part' => '56','id_car' => '2','id_gen' => '2'),
            array('id_part' => '56','id_car' => '2','id_gen' => '3'),
            array('id_part' => '56','id_car' => '8','id_gen' => '15'),
            array('id_part' => '56','id_car' => '3','id_gen' => '8'),
            array('id_part' => '56','id_car' => '3','id_gen' => '7'),
            array('id_part' => '56','id_car' => '6','id_gen' => '10'),
            array('id_part' => '56','id_car' => '6','id_gen' => '11'),
            array('id_part' => '56','id_car' => '5','id_gen' => '12'),
            array('id_part' => '56','id_car' => '5','id_gen' => '13'),
            array('id_part' => '56','id_car' => '7','id_gen' => '14'),
            array('id_part' => '56','id_car' => '9','id_gen' => '16'),
            array('id_part' => '59','id_car' => '4','id_gen' => '9'),
            array('id_part' => '59','id_car' => '2','id_gen' => '2'),
            array('id_part' => '59','id_car' => '2','id_gen' => '1'),
            array('id_part' => '59','id_car' => '3','id_gen' => '8'),
            array('id_part' => '59','id_car' => '3','id_gen' => '7'),
            array('id_part' => '60','id_car' => '2','id_gen' => '2'),
            array('id_part' => '60','id_car' => '2','id_gen' => '1'),
            array('id_part' => '60','id_car' => '3','id_gen' => '7'),
            array('id_part' => '61','id_car' => '2','id_gen' => '2'),
            array('id_part' => '61','id_car' => '2','id_gen' => '1'),
            array('id_part' => '62','id_car' => '2','id_gen' => '2'),
            array('id_part' => '62','id_car' => '2','id_gen' => '1'),
            array('id_part' => '63','id_car' => '4','id_gen' => '9'),
            array('id_part' => '63','id_car' => '2','id_gen' => '2'),
            array('id_part' => '63','id_car' => '2','id_gen' => '1'),
            array('id_part' => '63','id_car' => '3','id_gen' => '8'),
            array('id_part' => '64','id_car' => '2','id_gen' => '2'),
            array('id_part' => '64','id_car' => '2','id_gen' => '1'),
            array('id_part' => '65','id_car' => '2','id_gen' => '2'),
            array('id_part' => '65','id_car' => '2','id_gen' => '1'),
            array('id_part' => '66','id_car' => '2','id_gen' => '2'),
            array('id_part' => '66','id_car' => '2','id_gen' => '1'),
            array('id_part' => '67','id_car' => '2','id_gen' => '2'),
            array('id_part' => '67','id_car' => '2','id_gen' => '1'),
            array('id_part' => '68','id_car' => '4','id_gen' => '9'),
            array('id_part' => '68','id_car' => '2','id_gen' => '2'),
            array('id_part' => '68','id_car' => '2','id_gen' => '1'),
            array('id_part' => '68','id_car' => '3','id_gen' => '8'),
            array('id_part' => '68','id_car' => '3','id_gen' => '7'),
            array('id_part' => '69','id_car' => '2','id_gen' => '2'),
            array('id_part' => '69','id_car' => '2','id_gen' => '1'),
            array('id_part' => '70','id_car' => '2','id_gen' => '2'),
            array('id_part' => '70','id_car' => '2','id_gen' => '1'),
            array('id_part' => '71','id_car' => '2','id_gen' => '2'),
            array('id_part' => '71','id_car' => '2','id_gen' => '1'),
            array('id_part' => '73','id_car' => '4','id_gen' => '9'),
            array('id_part' => '73','id_car' => '8','id_gen' => '15'),
            array('id_part' => '73','id_car' => '3','id_gen' => '8'),
            array('id_part' => '73','id_car' => '3','id_gen' => '7'),
            array('id_part' => '73','id_car' => '6','id_gen' => '11'),
            array('id_part' => '73','id_car' => '5','id_gen' => '13'),
            array('id_part' => '73','id_car' => '7','id_gen' => '14'),
            array('id_part' => '73','id_car' => '9','id_gen' => '16'),
            array('id_part' => '74','id_car' => '4','id_gen' => '9'),
            array('id_part' => '74','id_car' => '3','id_gen' => '8'),
            array('id_part' => '75','id_car' => '3','id_gen' => '8'),
            array('id_part' => '76','id_car' => '4','id_gen' => '9'),
            array('id_part' => '76','id_car' => '3','id_gen' => '8'),
            array('id_part' => '76','id_car' => '3','id_gen' => '7'),
            array('id_part' => '76','id_car' => '7','id_gen' => '14'),
            array('id_part' => '77','id_car' => '4','id_gen' => '9'),
            array('id_part' => '77','id_car' => '2','id_gen' => '2'),
            array('id_part' => '77','id_car' => '2','id_gen' => '1'),
            array('id_part' => '77','id_car' => '8','id_gen' => '15'),
            array('id_part' => '77','id_car' => '3','id_gen' => '8'),
            array('id_part' => '77','id_car' => '3','id_gen' => '7'),
            array('id_part' => '77','id_car' => '6','id_gen' => '11'),
            array('id_part' => '77','id_car' => '5','id_gen' => '13'),
            array('id_part' => '77','id_car' => '7','id_gen' => '14'),
            array('id_part' => '78','id_car' => '4','id_gen' => '9'),
            array('id_part' => '78','id_car' => '2','id_gen' => '2'),
            array('id_part' => '78','id_car' => '2','id_gen' => '1'),
            array('id_part' => '78','id_car' => '3','id_gen' => '8'),
            array('id_part' => '78','id_car' => '3','id_gen' => '7'),
            array('id_part' => '79','id_car' => '2','id_gen' => '2'),
            array('id_part' => '79','id_car' => '2','id_gen' => '1'),
            array('id_part' => '80','id_car' => '2','id_gen' => '2'),
            array('id_part' => '80','id_car' => '2','id_gen' => '1'),
            array('id_part' => '81','id_car' => '2','id_gen' => '2'),
            array('id_part' => '81','id_car' => '2','id_gen' => '1'),
            array('id_part' => '83','id_car' => '4','id_gen' => '9'),
            array('id_part' => '83','id_car' => '2','id_gen' => '2'),
            array('id_part' => '83','id_car' => '2','id_gen' => '1'),
            array('id_part' => '83','id_car' => '8','id_gen' => '15'),
            array('id_part' => '83','id_car' => '3','id_gen' => '8'),
            array('id_part' => '83','id_car' => '3','id_gen' => '7'),
            array('id_part' => '83','id_car' => '6','id_gen' => '10'),
            array('id_part' => '83','id_car' => '6','id_gen' => '11'),
            array('id_part' => '83','id_car' => '5','id_gen' => '12'),
            array('id_part' => '83','id_car' => '5','id_gen' => '13'),
            array('id_part' => '83','id_car' => '7','id_gen' => '14'),
            array('id_part' => '83','id_car' => '9','id_gen' => '16'),
            array('id_part' => '84','id_car' => '2','id_gen' => '2'),
            array('id_part' => '84','id_car' => '2','id_gen' => '1'),
            array('id_part' => '100','id_car' => '2','id_gen' => '2'),
            array('id_part' => '101','id_car' => '4','id_gen' => '9'),
            array('id_part' => '101','id_car' => '2','id_gen' => '1'),
            array('id_part' => '102','id_car' => '4','id_gen' => '9'),
            array('id_part' => '102','id_car' => '3','id_gen' => '8'),
            array('id_part' => '103','id_car' => '4','id_gen' => '9'),
            array('id_part' => '103','id_car' => '2','id_gen' => '2'),
            array('id_part' => '103','id_car' => '2','id_gen' => '1'),
            array('id_part' => '103','id_car' => '8','id_gen' => '15'),
            array('id_part' => '103','id_car' => '3','id_gen' => '8'),
            array('id_part' => '103','id_car' => '3','id_gen' => '7'),
            array('id_part' => '103','id_car' => '6','id_gen' => '10'),
            array('id_part' => '103','id_car' => '6','id_gen' => '11'),
            array('id_part' => '103','id_car' => '5','id_gen' => '12'),
            array('id_part' => '103','id_car' => '5','id_gen' => '13'),
            array('id_part' => '103','id_car' => '7','id_gen' => '14'),
            array('id_part' => '103','id_car' => '9','id_gen' => '16'),
            array('id_part' => '104','id_car' => '2','id_gen' => '2'),
            array('id_part' => '104','id_car' => '2','id_gen' => '1'),
            array('id_part' => '104','id_car' => '3','id_gen' => '8'),
            array('id_part' => '104','id_car' => '3','id_gen' => '7'),
            array('id_part' => '105','id_car' => '2','id_gen' => '2'),
            array('id_part' => '105','id_car' => '2','id_gen' => '1'),
            array('id_part' => '105','id_car' => '3','id_gen' => '8'),
            array('id_part' => '105','id_car' => '3','id_gen' => '7'),
            array('id_part' => '106','id_car' => '4','id_gen' => '9'),
            array('id_part' => '106','id_car' => '2','id_gen' => '2'),
            array('id_part' => '106','id_car' => '2','id_gen' => '1'),
            array('id_part' => '106','id_car' => '3','id_gen' => '8'),
            array('id_part' => '106','id_car' => '3','id_gen' => '7'),
            array('id_part' => '107','id_car' => '2','id_gen' => '2'),
            array('id_part' => '107','id_car' => '2','id_gen' => '1'),
            array('id_part' => '107','id_car' => '3','id_gen' => '8'),
            array('id_part' => '107','id_car' => '3','id_gen' => '7'),
            array('id_part' => '108','id_car' => '2','id_gen' => '2'),
            array('id_part' => '108','id_car' => '2','id_gen' => '1'),
            array('id_part' => '108','id_car' => '3','id_gen' => '8'),
            array('id_part' => '108','id_car' => '3','id_gen' => '7'),
            array('id_part' => '109','id_car' => '4','id_gen' => '9'),
            array('id_part' => '109','id_car' => '2','id_gen' => '2'),
            array('id_part' => '109','id_car' => '2','id_gen' => '1'),
            array('id_part' => '109','id_car' => '8','id_gen' => '15'),
            array('id_part' => '109','id_car' => '3','id_gen' => '8'),
            array('id_part' => '109','id_car' => '3','id_gen' => '7'),
            array('id_part' => '109','id_car' => '6','id_gen' => '10'),
            array('id_part' => '109','id_car' => '6','id_gen' => '11'),
            array('id_part' => '109','id_car' => '5','id_gen' => '12'),
            array('id_part' => '109','id_car' => '5','id_gen' => '13'),
            array('id_part' => '109','id_car' => '7','id_gen' => '14'),
            array('id_part' => '109','id_car' => '9','id_gen' => '16'),
            array('id_part' => '110','id_car' => '2','id_gen' => '2'),
            array('id_part' => '110','id_car' => '2','id_gen' => '1'),
            array('id_part' => '111','id_car' => '2','id_gen' => '2'),
            array('id_part' => '111','id_car' => '2','id_gen' => '1'),
            array('id_part' => '112','id_car' => '2','id_gen' => '2'),
            array('id_part' => '112','id_car' => '2','id_gen' => '1'),
            array('id_part' => '113','id_car' => '4','id_gen' => '9'),
            array('id_part' => '113','id_car' => '2','id_gen' => '2'),
            array('id_part' => '113','id_car' => '2','id_gen' => '1'),
            array('id_part' => '113','id_car' => '8','id_gen' => '15'),
            array('id_part' => '113','id_car' => '3','id_gen' => '8'),
            array('id_part' => '113','id_car' => '3','id_gen' => '7'),
            array('id_part' => '113','id_car' => '6','id_gen' => '10'),
            array('id_part' => '113','id_car' => '6','id_gen' => '11'),
            array('id_part' => '113','id_car' => '5','id_gen' => '12'),
            array('id_part' => '113','id_car' => '5','id_gen' => '13'),
            array('id_part' => '113','id_car' => '7','id_gen' => '14'),
            array('id_part' => '113','id_car' => '9','id_gen' => '16'),
            array('id_part' => '114','id_car' => '4','id_gen' => '9'),
            array('id_part' => '114','id_car' => '2','id_gen' => '2'),
            array('id_part' => '114','id_car' => '2','id_gen' => '1'),
            array('id_part' => '114','id_car' => '8','id_gen' => '15'),
            array('id_part' => '114','id_car' => '3','id_gen' => '8'),
            array('id_part' => '114','id_car' => '3','id_gen' => '7'),
            array('id_part' => '114','id_car' => '6','id_gen' => '10'),
            array('id_part' => '114','id_car' => '6','id_gen' => '11'),
            array('id_part' => '114','id_car' => '5','id_gen' => '12'),
            array('id_part' => '114','id_car' => '5','id_gen' => '13'),
            array('id_part' => '114','id_car' => '7','id_gen' => '14'),
            array('id_part' => '114','id_car' => '9','id_gen' => '16'),
            array('id_part' => '115','id_car' => '4','id_gen' => '9'),
            array('id_part' => '115','id_car' => '3','id_gen' => '8'),
            array('id_part' => '115','id_car' => '3','id_gen' => '7'),
            array('id_part' => '115','id_car' => '6','id_gen' => '11'),
            array('id_part' => '115','id_car' => '7','id_gen' => '14'),
            array('id_part' => '116','id_car' => '4','id_gen' => '9'),
            array('id_part' => '116','id_car' => '3','id_gen' => '8'),
            array('id_part' => '116','id_car' => '3','id_gen' => '7'),
            array('id_part' => '117','id_car' => '4','id_gen' => '9'),
            array('id_part' => '117','id_car' => '3','id_gen' => '8'),
            array('id_part' => '117','id_car' => '3','id_gen' => '7'),
            array('id_part' => '117','id_car' => '6','id_gen' => '11'),
            array('id_part' => '117','id_car' => '7','id_gen' => '14'),
            array('id_part' => '118','id_car' => '2','id_gen' => '2'),
            array('id_part' => '118','id_car' => '2','id_gen' => '1'),
            array('id_part' => '119','id_car' => '4','id_gen' => '9'),
            array('id_part' => '119','id_car' => '3','id_gen' => '8'),
            array('id_part' => '119','id_car' => '3','id_gen' => '7'),
            array('id_part' => '120','id_car' => '2','id_gen' => '2'),
            array('id_part' => '120','id_car' => '2','id_gen' => '1'),
            array('id_part' => '121','id_car' => '2','id_gen' => '2'),
            array('id_part' => '121','id_car' => '2','id_gen' => '1'),
            array('id_part' => '122','id_car' => '2','id_gen' => '2'),
            array('id_part' => '122','id_car' => '2','id_gen' => '1'),
            array('id_part' => '123','id_car' => '2','id_gen' => '2'),
            array('id_part' => '123','id_car' => '2','id_gen' => '1'),
            array('id_part' => '124','id_car' => '2','id_gen' => '2'),
            array('id_part' => '124','id_car' => '3','id_gen' => '8'),
            array('id_part' => '124','id_car' => '5','id_gen' => '13'),
            array('id_part' => '125','id_car' => '2','id_gen' => '2'),
            array('id_part' => '125','id_car' => '3','id_gen' => '8'),
            array('id_part' => '125','id_car' => '5','id_gen' => '13'),
            array('id_part' => '126','id_car' => '2','id_gen' => '2'),
            array('id_part' => '126','id_car' => '3','id_gen' => '8'),
            array('id_part' => '126','id_car' => '5','id_gen' => '13'),
            array('id_part' => '127','id_car' => '2','id_gen' => '2'),
            array('id_part' => '127','id_car' => '3','id_gen' => '8'),
            array('id_part' => '127','id_car' => '5','id_gen' => '13'),
            array('id_part' => '128','id_car' => '2','id_gen' => '2'),
            array('id_part' => '128','id_car' => '3','id_gen' => '8'),
            array('id_part' => '128','id_car' => '5','id_gen' => '13'),
            array('id_part' => '129','id_car' => '2','id_gen' => '2'),
            array('id_part' => '129','id_car' => '3','id_gen' => '8'),
            array('id_part' => '129','id_car' => '5','id_gen' => '13'),
            array('id_part' => '130','id_car' => '2','id_gen' => '2'),
            array('id_part' => '130','id_car' => '3','id_gen' => '8'),
            array('id_part' => '130','id_car' => '5','id_gen' => '13'),
            array('id_part' => '131','id_car' => '2','id_gen' => '2'),
            array('id_part' => '131','id_car' => '3','id_gen' => '8'),
            array('id_part' => '131','id_car' => '5','id_gen' => '13'),
            array('id_part' => '132','id_car' => '2','id_gen' => '2'),
            array('id_part' => '132','id_car' => '3','id_gen' => '8'),
            array('id_part' => '132','id_car' => '5','id_gen' => '13'),
            array('id_part' => '133','id_car' => '2','id_gen' => '2'),
            array('id_part' => '133','id_car' => '3','id_gen' => '8'),
            array('id_part' => '133','id_car' => '5','id_gen' => '13'),
            array('id_part' => '134','id_car' => '2','id_gen' => '2'),
            array('id_part' => '134','id_car' => '3','id_gen' => '8'),
            array('id_part' => '134','id_car' => '5','id_gen' => '13'),
            array('id_part' => '135','id_car' => '4','id_gen' => '9'),
            array('id_part' => '135','id_car' => '2','id_gen' => '2'),
            array('id_part' => '135','id_car' => '2','id_gen' => '1'),
            array('id_part' => '135','id_car' => '8','id_gen' => '15'),
            array('id_part' => '135','id_car' => '3','id_gen' => '8'),
            array('id_part' => '135','id_car' => '3','id_gen' => '7'),
            array('id_part' => '135','id_car' => '6','id_gen' => '10'),
            array('id_part' => '135','id_car' => '6','id_gen' => '11'),
            array('id_part' => '135','id_car' => '5','id_gen' => '12'),
            array('id_part' => '135','id_car' => '5','id_gen' => '13'),
            array('id_part' => '135','id_car' => '7','id_gen' => '14'),
            array('id_part' => '135','id_car' => '9','id_gen' => '16'),
            array('id_part' => '136','id_car' => '2','id_gen' => '2'),
            array('id_part' => '136','id_car' => '2','id_gen' => '1'),
            array('id_part' => '137','id_car' => '2','id_gen' => '2'),
            array('id_part' => '137','id_car' => '2','id_gen' => '1'),
            array('id_part' => '138','id_car' => '2','id_gen' => '2'),
            array('id_part' => '138','id_car' => '2','id_gen' => '1'),
            array('id_part' => '139','id_car' => '2','id_gen' => '2'),
            array('id_part' => '139','id_car' => '2','id_gen' => '1'),
            array('id_part' => '140','id_car' => '2','id_gen' => '2'),
            array('id_part' => '140','id_car' => '2','id_gen' => '1'),
            array('id_part' => '141','id_car' => '2','id_gen' => '2'),
            array('id_part' => '141','id_car' => '2','id_gen' => '1'),
            array('id_part' => '142','id_car' => '2','id_gen' => '2'),
            array('id_part' => '142','id_car' => '2','id_gen' => '1'),
            array('id_part' => '143','id_car' => '2','id_gen' => '2'),
            array('id_part' => '143','id_car' => '2','id_gen' => '1'),
            array('id_part' => '144','id_car' => '2','id_gen' => '2'),
            array('id_part' => '144','id_car' => '2','id_gen' => '1'),
            array('id_part' => '145','id_car' => '4','id_gen' => '9'),
            array('id_part' => '145','id_car' => '2','id_gen' => '2'),
            array('id_part' => '146','id_car' => '4','id_gen' => '9'),
            array('id_part' => '146','id_car' => '2','id_gen' => '2'),
            array('id_part' => '147','id_car' => '4','id_gen' => '9'),
            array('id_part' => '147','id_car' => '2','id_gen' => '2'),
            array('id_part' => '148','id_car' => '2','id_gen' => '2'),
            array('id_part' => '148','id_car' => '2','id_gen' => '1'),
            array('id_part' => '149','id_car' => '2','id_gen' => '2'),
            array('id_part' => '149','id_car' => '2','id_gen' => '1'),
            array('id_part' => '150','id_car' => '2','id_gen' => '2'),
            array('id_part' => '150','id_car' => '2','id_gen' => '1'),
            array('id_part' => '151','id_car' => '2','id_gen' => '2'),
            array('id_part' => '151','id_car' => '2','id_gen' => '1'),
            array('id_part' => '152','id_car' => '2','id_gen' => '2'),
            array('id_part' => '152','id_car' => '2','id_gen' => '1'),
            array('id_part' => '153','id_car' => '2','id_gen' => '2'),
            array('id_part' => '153','id_car' => '2','id_gen' => '1'),
            array('id_part' => '154','id_car' => '2','id_gen' => '2'),
            array('id_part' => '154','id_car' => '2','id_gen' => '1'),
            array('id_part' => '155','id_car' => '2','id_gen' => '2'),
            array('id_part' => '156','id_car' => '2','id_gen' => '2'),
            array('id_part' => '156','id_car' => '2','id_gen' => '1'),
            array('id_part' => '157','id_car' => '2','id_gen' => '2'),
            array('id_part' => '157','id_car' => '2','id_gen' => '1'),
            array('id_part' => '158','id_car' => '2','id_gen' => '2'),
            array('id_part' => '158','id_car' => '2','id_gen' => '1'),
            array('id_part' => '159','id_car' => '2','id_gen' => '2'),
            array('id_part' => '159','id_car' => '2','id_gen' => '1'),
            array('id_part' => '160','id_car' => '2','id_gen' => '2'),
            array('id_part' => '160','id_car' => '2','id_gen' => '1'),
            array('id_part' => '160','id_car' => '3','id_gen' => '8'),
            array('id_part' => '160','id_car' => '3','id_gen' => '7'),
            array('id_part' => '160','id_car' => '6','id_gen' => '10'),
            array('id_part' => '160','id_car' => '6','id_gen' => '11'),
            array('id_part' => '160','id_car' => '5','id_gen' => '12'),
            array('id_part' => '160','id_car' => '5','id_gen' => '13'),
            array('id_part' => '161','id_car' => '2','id_gen' => '2'),
            array('id_part' => '161','id_car' => '2','id_gen' => '1'),
            array('id_part' => '161','id_car' => '3','id_gen' => '8'),
            array('id_part' => '161','id_car' => '3','id_gen' => '7'),
            array('id_part' => '161','id_car' => '6','id_gen' => '10'),
            array('id_part' => '161','id_car' => '6','id_gen' => '11'),
            array('id_part' => '161','id_car' => '5','id_gen' => '12'),
            array('id_part' => '161','id_car' => '5','id_gen' => '13'),
            array('id_part' => '162','id_car' => '2','id_gen' => '2'),
            array('id_part' => '162','id_car' => '2','id_gen' => '1'),
            array('id_part' => '163','id_car' => '2','id_gen' => '2'),
            array('id_part' => '163','id_car' => '2','id_gen' => '1'),
            array('id_part' => '164','id_car' => '2','id_gen' => '2'),
            array('id_part' => '164','id_car' => '2','id_gen' => '1'),
            array('id_part' => '165','id_car' => '2','id_gen' => '2'),
            array('id_part' => '165','id_car' => '2','id_gen' => '1'),
            array('id_part' => '165','id_car' => '3','id_gen' => '8'),
            array('id_part' => '165','id_car' => '3','id_gen' => '7'),
            array('id_part' => '165','id_car' => '6','id_gen' => '10'),
            array('id_part' => '165','id_car' => '5','id_gen' => '12'),
            array('id_part' => '165','id_car' => '5','id_gen' => '13'),
            array('id_part' => '166','id_car' => '2','id_gen' => '2'),
            array('id_part' => '166','id_car' => '2','id_gen' => '1'),
            array('id_part' => '166','id_car' => '3','id_gen' => '8'),
            array('id_part' => '166','id_car' => '3','id_gen' => '7'),
            array('id_part' => '167','id_car' => '2','id_gen' => '2'),
            array('id_part' => '167','id_car' => '2','id_gen' => '1'),
            array('id_part' => '167','id_car' => '3','id_gen' => '8'),
            array('id_part' => '167','id_car' => '3','id_gen' => '7'),
            array('id_part' => '168','id_car' => '2','id_gen' => '2'),
            array('id_part' => '168','id_car' => '2','id_gen' => '1'),
            array('id_part' => '169','id_car' => '2','id_gen' => '1'),
            array('id_part' => '170','id_car' => '2','id_gen' => '2'),
            array('id_part' => '171','id_car' => '2','id_gen' => '2'),
            array('id_part' => '171','id_car' => '2','id_gen' => '1'),
            array('id_part' => '172','id_car' => '4','id_gen' => '9'),
            array('id_part' => '172','id_car' => '3','id_gen' => '8'),
            array('id_part' => '173','id_car' => '4','id_gen' => '9'),
            array('id_part' => '173','id_car' => '3','id_gen' => '8'),
            array('id_part' => '173','id_car' => '7','id_gen' => '14'),
            array('id_part' => '174','id_car' => '4','id_gen' => '9'),
            array('id_part' => '174','id_car' => '3','id_gen' => '8'),
            array('id_part' => '174','id_car' => '3','id_gen' => '7'),
            array('id_part' => '174','id_car' => '7','id_gen' => '14'),
            array('id_part' => '175','id_car' => '4','id_gen' => '9'),
            array('id_part' => '175','id_car' => '3','id_gen' => '8'),
            array('id_part' => '176','id_car' => '4','id_gen' => '9'),
            array('id_part' => '176','id_car' => '3','id_gen' => '8'),
            array('id_part' => '177','id_car' => '4','id_gen' => '9'),
            array('id_part' => '177','id_car' => '3','id_gen' => '8'),
            array('id_part' => '178','id_car' => '4','id_gen' => '9'),
            array('id_part' => '178','id_car' => '3','id_gen' => '8'),
            array('id_part' => '178','id_car' => '3','id_gen' => '7'),
            array('id_part' => '179','id_car' => '2','id_gen' => '2'),
            array('id_part' => '179','id_car' => '2','id_gen' => '1'),
            array('id_part' => '179','id_car' => '3','id_gen' => '7'),
            array('id_part' => '179','id_car' => '6','id_gen' => '10'),
            array('id_part' => '179','id_car' => '5','id_gen' => '12'),
            array('id_part' => '180','id_car' => '3','id_gen' => '7'),
            array('id_part' => '181','id_car' => '3','id_gen' => '7'),
            array('id_part' => '182','id_car' => '3','id_gen' => '7'),
            array('id_part' => '183','id_car' => '3','id_gen' => '7'),
            array('id_part' => '184','id_car' => '4','id_gen' => '9'),
            array('id_part' => '184','id_car' => '3','id_gen' => '8'),
            array('id_part' => '185','id_car' => '2','id_gen' => '2'),
            array('id_part' => '185','id_car' => '2','id_gen' => '1'),
            array('id_part' => '185','id_car' => '3','id_gen' => '7'),
            array('id_part' => '188','id_car' => '8','id_gen' => '15'),
            array('id_part' => '188','id_car' => '7','id_gen' => '14'),
            array('id_part' => '189','id_car' => '8','id_gen' => '15'),
            array('id_part' => '189','id_car' => '7','id_gen' => '14'),
            array('id_part' => '190','id_car' => '8','id_gen' => '15'),
            array('id_part' => '190','id_car' => '7','id_gen' => '14'),
            array('id_part' => '191','id_car' => '8','id_gen' => '15'),
            array('id_part' => '191','id_car' => '7','id_gen' => '14'),
            array('id_part' => '192','id_car' => '8','id_gen' => '15'),
            array('id_part' => '192','id_car' => '6','id_gen' => '11'),
            array('id_part' => '192','id_car' => '7','id_gen' => '14'),
            array('id_part' => '192','id_car' => '9','id_gen' => '16'),
            array('id_part' => '193','id_car' => '8','id_gen' => '15'),
            array('id_part' => '193','id_car' => '6','id_gen' => '11'),
            array('id_part' => '193','id_car' => '7','id_gen' => '14'),
            array('id_part' => '194','id_car' => '8','id_gen' => '15'),
            array('id_part' => '194','id_car' => '6','id_gen' => '11'),
            array('id_part' => '194','id_car' => '7','id_gen' => '14'),
            array('id_part' => '195','id_car' => '8','id_gen' => '15'),
            array('id_part' => '195','id_car' => '7','id_gen' => '14'),
            array('id_part' => '196','id_car' => '8','id_gen' => '15'),
            array('id_part' => '196','id_car' => '7','id_gen' => '14'),
            array('id_part' => '197','id_car' => '8','id_gen' => '15'),
            array('id_part' => '197','id_car' => '7','id_gen' => '14'),
            array('id_part' => '198','id_car' => '8','id_gen' => '15'),
            array('id_part' => '198','id_car' => '7','id_gen' => '14'),
            array('id_part' => '199','id_car' => '8','id_gen' => '15'),
            array('id_part' => '199','id_car' => '7','id_gen' => '14'),
            array('id_part' => '200','id_car' => '8','id_gen' => '15'),
            array('id_part' => '200','id_car' => '7','id_gen' => '14'),
            array('id_part' => '200','id_car' => '9','id_gen' => '16'),
            array('id_part' => '201','id_car' => '8','id_gen' => '15'),
            array('id_part' => '201','id_car' => '7','id_gen' => '14'),
            array('id_part' => '202','id_car' => '8','id_gen' => '15'),
            array('id_part' => '202','id_car' => '7','id_gen' => '14'),
            array('id_part' => '202','id_car' => '9','id_gen' => '16'),
            array('id_part' => '203','id_car' => '8','id_gen' => '15'),
            array('id_part' => '203','id_car' => '7','id_gen' => '14'),
            array('id_part' => '203','id_car' => '9','id_gen' => '16'),
            array('id_part' => '204','id_car' => '8','id_gen' => '15'),
            array('id_part' => '204','id_car' => '6','id_gen' => '11'),
            array('id_part' => '204','id_car' => '7','id_gen' => '14'),
            array('id_part' => '204','id_car' => '9','id_gen' => '16'),
            array('id_part' => '205','id_car' => '8','id_gen' => '15'),
            array('id_part' => '205','id_car' => '6','id_gen' => '11'),
            array('id_part' => '205','id_car' => '7','id_gen' => '14'),
            array('id_part' => '205','id_car' => '9','id_gen' => '16'),
            array('id_part' => '206','id_car' => '8','id_gen' => '15'),
            array('id_part' => '206','id_car' => '6','id_gen' => '11'),
            array('id_part' => '206','id_car' => '5','id_gen' => '13'),
            array('id_part' => '206','id_car' => '7','id_gen' => '14'),
            array('id_part' => '206','id_car' => '9','id_gen' => '16'),
            array('id_part' => '207','id_car' => '8','id_gen' => '15'),
            array('id_part' => '207','id_car' => '7','id_gen' => '14'),
            array('id_part' => '207','id_car' => '9','id_gen' => '16'),
            array('id_part' => '208','id_car' => '8','id_gen' => '15'),
            array('id_part' => '208','id_car' => '7','id_gen' => '14'),
            array('id_part' => '208','id_car' => '9','id_gen' => '16'),
            array('id_part' => '209','id_car' => '8','id_gen' => '15'),
            array('id_part' => '209','id_car' => '7','id_gen' => '14'),
            array('id_part' => '209','id_car' => '9','id_gen' => '16'),
            array('id_part' => '210','id_car' => '8','id_gen' => '15'),
            array('id_part' => '210','id_car' => '6','id_gen' => '11'),
            array('id_part' => '210','id_car' => '7','id_gen' => '14'),
            array('id_part' => '210','id_car' => '9','id_gen' => '16'),
            array('id_part' => '211','id_car' => '8','id_gen' => '15'),
            array('id_part' => '211','id_car' => '6','id_gen' => '11'),
            array('id_part' => '211','id_car' => '7','id_gen' => '14'),
            array('id_part' => '211','id_car' => '9','id_gen' => '16'),
            array('id_part' => '212','id_car' => '8','id_gen' => '15'),
            array('id_part' => '212','id_car' => '7','id_gen' => '14'),
            array('id_part' => '212','id_car' => '9','id_gen' => '16'),
            array('id_part' => '213','id_car' => '8','id_gen' => '15'),
            array('id_part' => '213','id_car' => '6','id_gen' => '11'),
            array('id_part' => '213','id_car' => '7','id_gen' => '14'),
            array('id_part' => '213','id_car' => '9','id_gen' => '16'),
            array('id_part' => '214','id_car' => '8','id_gen' => '15'),
            array('id_part' => '214','id_car' => '6','id_gen' => '11'),
            array('id_part' => '214','id_car' => '7','id_gen' => '14'),
            array('id_part' => '214','id_car' => '9','id_gen' => '16'),
            array('id_part' => '215','id_car' => '8','id_gen' => '15'),
            array('id_part' => '215','id_car' => '6','id_gen' => '11'),
            array('id_part' => '215','id_car' => '7','id_gen' => '14'),
            array('id_part' => '215','id_car' => '9','id_gen' => '16'),
            array('id_part' => '216','id_car' => '5','id_gen' => '13'),
            array('id_part' => '216','id_car' => '7','id_gen' => '14'),
            array('id_part' => '217','id_car' => '5','id_gen' => '13'),
            array('id_part' => '217','id_car' => '7','id_gen' => '14'),
            array('id_part' => '218','id_car' => '5','id_gen' => '13'),
            array('id_part' => '218','id_car' => '7','id_gen' => '14'),
            array('id_part' => '219','id_car' => '7','id_gen' => '14'),
            array('id_part' => '220','id_car' => '7','id_gen' => '14'),
            array('id_part' => '221','id_car' => '7','id_gen' => '14'),
            array('id_part' => '222','id_car' => '7','id_gen' => '14'),
            array('id_part' => '223','id_car' => '7','id_gen' => '14'),
            array('id_part' => '224','id_car' => '8','id_gen' => '15'),
            array('id_part' => '224','id_car' => '6','id_gen' => '11'),
            array('id_part' => '224','id_car' => '7','id_gen' => '14'),
            array('id_part' => '224','id_car' => '9','id_gen' => '16'),
            array('id_part' => '225','id_car' => '8','id_gen' => '15'),
            array('id_part' => '225','id_car' => '7','id_gen' => '14'),
            array('id_part' => '225','id_car' => '9','id_gen' => '16'),
            array('id_part' => '226','id_car' => '4','id_gen' => '9'),
            array('id_part' => '226','id_car' => '2','id_gen' => '2'),
            array('id_part' => '226','id_car' => '2','id_gen' => '1'),
            array('id_part' => '226','id_car' => '8','id_gen' => '15'),
            array('id_part' => '226','id_car' => '3','id_gen' => '8'),
            array('id_part' => '226','id_car' => '3','id_gen' => '7'),
            array('id_part' => '226','id_car' => '6','id_gen' => '10'),
            array('id_part' => '226','id_car' => '6','id_gen' => '11'),
            array('id_part' => '226','id_car' => '5','id_gen' => '12'),
            array('id_part' => '226','id_car' => '5','id_gen' => '13'),
            array('id_part' => '226','id_car' => '7','id_gen' => '14'),
            array('id_part' => '226','id_car' => '9','id_gen' => '16')
          );
        
        foreach($srv_parts as $key => $value){
            foreach($srv_parts_cars as $k => $v){
                if($v['id_part' == $value['id_part']]){
                    $srv_parts[$key]['car_id'][] = 
                }
            }
        }
        return $srv_parts;
    }
}
